name: 'dbttransform'
version: '1.0.0'

profile: 'dbttransform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

models:
  dbttransform:
    raw:
      +materialized: view
    staging:
      +materialized: table
