
version: 2

models:
  - name: raw_movies
    description: "A raw movies from mongodb sample data"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

